language: java

sudo: true

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

services:
  - docker

jdk:
  - oraclejdk9

before_install:
  - mkdir -p $HOME/.gradle/ && openssl aes-256-cbc -K $encrypted_4c209f73aa5c_key -iv $encrypted_4c209f73aa5c_iv -in gradle.properties.enc -out $HOME/.gradle/gradle.properties -d || true
  - (openssl aes-256-cbc -K $encrypted_4c209f73aa5c_key -iv $encrypted_4c209f73aa5c_iv -in signing.gpg.enc -d | gpg --import) || true

# Don't run eval ./gradlew assemble"
install:
  - ./gradlew examples:geoserverData

script:
  - git --no-pager diff --check `git log --oneline | tail -1 | cut --fields=1 --delimiter=' '`
  - .travis/test-eof-newline
  - ./gradlew build

after_failure:
  - cat core/build/reports/tests/index.html
  - sh travis/print-examples-test-output.sh

deploy:
  - provider: script
    script: travis/publish.sh
    skip_cleanup: true
    on:
      repo: mapfish/mapfish-print
      java: oraclejdk8
      all_branches: true

notifications:
  email:
    recipients:
      - stephane.brunner@camptocamp.com
