# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1

orbs:
  gradle: circleci/gradle@1.0.10

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      TERM: dumb

    steps:
      - checkout

      - run:
          command: sudo apt update
      - run:
          name: Install OS dependencies
          command: sudo apt install ttf-liberation

      - run: git --no-pager diff --check `git log --oneline | tail -1 | cut --fields=1 --delimiter=' '`

      - run: circleci/test-eof-newline

      - gradle/with_cache:
          steps:
            - run:
                name: Build
                command: ./gradlew build

      - store_artifacts:
          path: examples/build/reports
          destination: reports
      - store_artifacts:
          path: core/build/reports
          destination: reports
      - run:
          name: Collect test results
          command: |
            mkdir -p /tmp/test_results/junit
            find . -name '*TEST-*.xml' -exec cp -v {} /tmp/test_results/junit/ \;
          when: always
      - store_test_results:
          path: /tmp/test_results

      - run:
          name: Decrypt secrets
          command: |
            set -e
            mkdir -p $HOME/.gradle/
            openssl aes-256-cbc -K $AES_KEY -iv $AES_IV -in circleci/gradle.properties.enc -out ~/.gradle/gradle.properties -d
            openssl aes-256-cbc -K $AES_KEY -iv $AES_IV -in circleci/signing.gpg.enc -d | gpg --import || true
            openssl aes-256-cbc -K $AES_KEY -iv $AES_IV -in circleci/signing.gpg.enc -d > ~/.gnupg/secring.gpg
            openssl aes-256-cbc -K $AES_KEY -iv $AES_IV -in circleci/dockercfg.enc -out ~/.dockercfg -d

      - setup_remote_docker

      - run:
          name: publish
          command: circleci/publish.sh
workflows:
  version: 2
  push:
    jobs: &jobs
      - build

  tag_push:
    jobs: &jobs
      - build:
          filters:
            tags:
              only: /^release\/\d+\.\d+\.\d+/
            branches:
              ignore: /.*/

  nightly:
    triggers:
      - schedule:
          cron: 0 0 * * *
          filters:
            branches:
              only:
                - master
                - /3\.\d+/
    jobs: *jobs
